#!/usr/bin/env bash
if [[ $# -eq 0 ]] ; then
    echo 'A server jar must be supplied as the first argument.'
    exit 1
fi

if [[ ! -e $1 ]] ; then
    echo "The supplied jar file '$1' must exist."
    exit 1
fi

stopping=0
trap 'stopping=1' INT TERM

while true; do
#auto-restart until ctrl-c or exit 0
java -XX:+HeapDumpOnOutOfMemoryError -jar "$1"
excode=$?
if [ $stopping -eq 1 ] || [ $excode -eq 0 ] || [ $excode -eq 130 ] || [ $excode -eq 143 ]; then
  exit 0
fi
done
